#ifndef GAMESMODULE_GLOBAL_H
#define GAMESMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAMESMODULE_LIBRARY)
#  define GAMESMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAMESMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GAMESMODULE_GLOBAL_H
